Update git submodules
* Update skins/Vector from branch 'wmf/1.39.0-wmf.4'
  to f1f6c1db003e78a9ca6e9e0352b6fc567cc3fc39
  - Revert "End migration mode"
    
    This reverts commit 40b8558adff476c12cd507ca3e5441d54f18cf1c.
    
    Reason for revert: caused errors in production
       Error: Class 'Vector\SkinVersionLookup' not found
    
    Change-Id: I5faa79f53f288285ae71dea10a33dd7fc62a0baa